### ISSUE TITLE
Be sure and take new screenshots with newest PySimpleGUI

### ISSUE THREAD

**Issue by PySimpleGUI** [pyIDM/pyIDM#6]
You'll want to take new screenshots with the latest PySimpleGUI because of much better styling of things like the Tabs.  Now tabs are auto colored based on the Theme.  Since you allow the user to set the theme, this will really work out well for you.

Check out this nice looking main screen now.

![image](https://user-images.githubusercontent.com/46163555/70858029-aa238080-1ec7-11ea-808d-fa0f145d66a1.png)

**Comment by Aboghazala** [comment]
wow!, it looks good, i forgot about these tabs colors, this was missing before, now it is much better
will make new set of screenshots

Thanks Mike for these advises, really appreciate that.

**Comment by PySimpleGUI** [comment]
You've got control over the tab colors if you don't like the ones the theme has chosen for you.  I used a combination of the 3 different colors available in the theme to create the selected-tab and normal tab colors.  It was tricky to build the logic for it, but it does seem to work with all of the color themes, at least for 50 or more I tested.

**Comment by Aboghazala** [comment]
Done, Added new set of screenshots

**Comment by PySimpleGUI** [comment]
I just posted to GitHub a new version of PySimpleGUI that supports Table and Tree element header colors.  Like tabs and other stuff, it will default the colors to be what's in the Look and Feel table.

Check out your new screenshot!

![image](https://user-images.githubusercontent.com/46163555/71052967-fc101480-211a-11ea-9b6e-185806cd0ed4.png)

Here it is in Dark Red

![image](https://user-images.githubusercontent.com/46163555/71053049-3aa5cf00-211b-11ea-9a47-1f51f4c4f576.png)


As you can see, I'm using the same color scheme for the headers as I do for tabs.  They are actually the same as the Input color and the Input Text color.  That way I know they'll match and are not the same as the background.

**Comment by PySimpleGUI** [comment]
Oh, I should also mention that tabs and these headers all support changing the font and font size.  So if you're using other fonts and sizes of fonts throughout your GUI, you might want to use those for the headers too.  Hmmmm.... maybe I should default the font to be the window font if one isn't specified.  Have to think on this.

**Comment by Aboghazala** [comment]
These table header colors is a great addition to theme section, now it feels more native to the the selected theme, 
and the font it would be the right thing to be defaulted to window font
good job :))

**Comment by PySimpleGUI** [comment]
OK, I've released 4.13.0 to PyPI.  It has the header colors and font thing in there so that your windows should now automatically match regardless of the color theme chosen.

If you get one from my GitHub then I would suggest deleting it and grabbing the latest via pip.

I like the new PyIDM name! I was able to look you up a lot quicker searching this time.  I could have looked at my history, but was more fun to type "PyIDM" and see it come up.  😃

**Comment by pyIDM** [comment]
This is a great work, themes are on of the strength points of pySimpleGUI. i will update thru pip

Finally, i managed to transfer my repo to the new user name "pyIDM", it sits now under 
[github.com/pyIDM/pyIDM](github.com/pyIDM/pyIDM) and the old link will redirect automatically to this new one,
also managed to make repo size 1.5 MB instead of 188 MB because of these binaries were filling .git history
i will check if i messed up any other history commits before and do some tests before I drop a post in r/python :))

**Comment by PySimpleGUI** [comment]
Your comment made me realize that I'm not getting the default font for the headers from the window settings.  I've fixed that and checked it in, but it's not part of the 4.13 release of course.

I also need to look at the sizes of my repo!  I'm downloading the ZIP now and it's 90MB.  WOW.  That's not good.

I moved PySimpleGUI from another account over to PySimpleGUI/PySimpleGUI and was able to keep all of the information about development intact.  It wasn't long ago that I switch all development over from my personal account too.

![image](https://user-images.githubusercontent.com/46163555/71192739-dee06080-2256-11ea-988b-811ec18850d8.png)

**Comment by pyIDM** [comment]
> Your comment made me realize that I'm not getting the default font for the headers from the window settings. I've fixed that and checked it in, but it's not part of the 4.13 release of course.

it sounds good :)) :+1: 

it is too much headache to keep the repo size small, especially if you include images, or in my case a binary file, for the later i found the proper place for them will be under releases section of the repo, but for images and snapshots still don't know a proper way to store them on github and in the same time keep them away from git history

**Comment by pyIDM** [comment]
created a reddit account and tried to make a post in r/python but got the message: `Your reddit account must be older than 2 weeks before you can post`
I think i will post it later after 2 weeks.
